name = "CreateGuido"
author = "Lucce Guido 2"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03068ec2a522c9c9a633fa0657388b763581eb33c1a27ab85a11e18dfa88c417"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
