name = "CreateGuido"
author = "Lucce Guido 2"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c600a731aae21f0bf49c8e3047048277fb7b5fc78879cbc712b85f91502bb27"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
