name = "CreateGuido"
author = "Lucce Guido 2"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6ffed11cf40d1fae4f13b276f110b533f94943615f52e28590ebc86138002a4"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
